#!/bin/bash
#SBATCH --job-name=calcRangeOffset_set13
#SBATCH --account=nc57
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem-per-cpu=16128
#SBATCH --partition=comp
#SBATCH --time=96:00:00
#SBATCH --mail-type=BEGIN,FAIL,END
#SBATCH --mail-user=david.clarke1@monash.edu
#SBATCH --output=calcRangeOffset_set13.txt
cd nc57/Chapter_3/Scripts
module load R/4.1.0-mkl
export R_LIBS=~/R/libs
module load udunits2/2.2.20-2
module load gdal/3.0.2
module load proj/6.2.1
module load geos/3.7.2
R --vanilla < calc_range_offset_cluster13.R