#!/bin/bash
#SBATCH --job-name=species_area_wgt_CAZ_run
#SBATCH --account=nc57
#SBATCH --ntasks=4
#SBATCH --mem=128G
#SBATCH --partition=comp
#SBATCH --time=24:00:00
#SBATCH --mail-type=BEGIN,FAIL,END
#SBATCH --mail-user=david.clarke1@monash.edu
#SBATCH --output=species_area_wgt_CAZ_run.txt
cd /home/dcla0008/nc57_scratch/Zonation/species_area_wgt_CAZ_proj
module load zonation/4.0.0
module load udunits2/2.2.20-2
module load gdal/3.0.2
module load proj/6.2.1
module load geos/3.7.2
sh ./species_area_wgt_CAZ.sh



